resolver: lts-16.17

packages:
 - .

extra-deps:
 - /home/andrew/src/aesiniath/unbeliever/core-text
 - /home/andrew/src/aesiniath/unbeliever/core-program
 - /home/andrew/src/aesiniath/unbeliever/core-data
 - ivar-simple-0.3.2

build:
  haddock: false

nix:
  packages: [openssl]
